name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deneme:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Command
      run: echo Github Action

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Build the Docker image
      with:
        image: docker:19.03.12
        run: |
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)
          docker images
