name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: hasanertenli13
        password: dckr_pat_JhoReBYQxOyKb0XPaLriWtfbdDk
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Set up Docker Build
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ../Dockerfile
        push: true
        tags: hasanertenli13/github-action-test:latest
